export const Routes = {
  // pages:
  // Presentation: { path: "/" },
  // Login: { path: "/" },
  DashboardOverview: { path: "/" },
  Transactions: { path: "/transactions" },
  Advertisement: { path: "/advertisement" },
  Users: { path: "/users" },
  NewOrder: { path: "/user/:userId/order" },
  User: { path: "/user/:userId" },
  Orders: { path: "/orders" },
  Order: { path: "/order/:ref" },
  Awords: { path: "/awords" },
  Team: {path: "/team"},
  Listings: { path: "/listings" },
  Events: {path: "/posts_events" },
  Event: {path: "/posts_events/:id" },
  TopicalPages: {path: "/topicalPages"},
  Messages: {path: "/messages" },
  AgroCommodityPricesPage: {path: "/pages/commodities"},
  ForexRates: {path: "/pages/forex_rates"},
  Manuals: {path: "/pages/guides"},
  Testimonials: {path: "/pages/testimonials"},
  Partners:  {path: "/pages/partners"},
  Settings: { path: "/settings" },
  //settings drop
  UserCategories:{path: "/users/categories"},
  ProductCategories: {path: "/products/categories"},
  SubCategories: {path: "/products/sub_categories/:id"}, 
  Regions: {path: "/regions" },
  Districts: {path: "/districts" },
  Rates: {path: "/membership_rates"},
  Admins: {path: "/admins"},
  Admin:{path: "/admin/:id"},
  ForgotPassword: { path: "/forgot-password" },
  ResetPassword: { path: "/reset-password" },
  Lock: { path: "/lock" },
  NotFound: { path: "/404" },
  ServerError: { path: "/500" },

  // docs
  DocsOverview: { path: "/documentation/overview" },
  DocsDownload: { path: "/documentation/download" },
  DocsQuickStart: { path: "/documentation/quick-start" },
  DocsLicense: { path: "/documentation/license" },
  DocsFolderStructure: { path: "/documentation/folder-structure" },
  DocsBuild: { path: "/documentation/build-tools" },
  DocsChangelog: { path: "/documentation/changelog" },

  // components
  Accordions: { path: "/components/accordions" },
  Alerts: { path: "/components/alerts" },
  Badges: { path: "/components/badges" },
  Widgets: { path: "/widgets" },
  Breadcrumbs: { path: "/components/breadcrumbs" },
  Buttons: { path: "/components/buttons" },
  Forms: { path: "/components/forms" },
  Modals: { path: "/components/modals" },
  Navs: { path: "/components/navs" },
  Navbars: { path: "/components/navbars" },
  Pagination: { path: "/components/pagination" },
  Popovers: { path: "/components/popovers" },
  Progress: { path: "/components/progress" },
  // Tables: { path: "/components/tables" },
  Tabs: { path: "/components/tabs" },
  Tooltips: { path: "/components/tooltips" },
  Toasts: { path: "/components/toasts" },
  WidgetsComponent: { path: "/components/widgets" },
};
